"""Univers du Screener de Clément : SMI (complet) + principaux constituants
du Stoxx Europe 600, en format ticker Yahoo Finance.

Le filtre de capitalisation (> seuil) écrête naturellement la longue traîne
du Stoxx 600 : seules les large/mid caps "sur lesquelles on poserait un
million sans sourciller" ressortent. La liste vise donc l'exhaustivité utile
(grandes valeurs européennes + suisses, tous secteurs/pays), pas les ~600
lignes dont beaucoup sous le seuil.

Format : (ticker_yahoo, nom, pays_ISO, secteur_court_FR)
"""

# Taux de change approximatifs → EUR (pour normaliser marketCap).
# Affinables ; suffisant pour un filtre de capitalisation.
FX_TO_EUR = {
    "EUR": 1.0, "CHF": 1.05, "GBP": 1.17, "GBp": 0.0117, "GBX": 0.0117,
    "SEK": 0.088, "DKK": 0.134, "NOK": 0.086, "USD": 0.92,
    "PLN": 0.235, "CZK": 0.040, "ILS": 0.25,
}

TICKERS = [
    # ── Suisse — SMI 20 (complet) ──
    ("NESN.SW", "Nestlé", "CH", "Conso. déf."),
    ("ROG.SW", "Roche", "CH", "Santé"),
    ("NOVN.SW", "Novartis", "CH", "Santé"),
    ("UBSG.SW", "UBS Group", "CH", "Finance"),
    ("ZURN.SW", "Zurich Insurance", "CH", "Assurance"),
    ("ABBN.SW", "ABB", "CH", "Industrie"),
    ("LONN.SW", "Lonza", "CH", "Santé"),
    ("SIKA.SW", "Sika", "CH", "Matériaux"),
    ("GIVN.SW", "Givaudan", "CH", "Matériaux"),
    ("HOLN.SW", "Holcim", "CH", "Matériaux"),
    ("ALC.SW", "Alcon", "CH", "Santé"),
    ("PGHN.SW", "Partners Group", "CH", "Finance"),
    ("SREN.SW", "Swiss Re", "CH", "Assurance"),
    ("SLHN.SW", "Swiss Life", "CH", "Assurance"),
    ("GEBN.SW", "Geberit", "CH", "Industrie"),
    ("SOON.SW", "Sonova", "CH", "Santé"),
    ("CFR.SW", "Richemont", "CH", "Luxe"),
    ("LOGN.SW", "Logitech", "CH", "Tech"),
    ("KNIN.SW", "Kühne+Nagel", "CH", "Industrie"),
    ("SCMN.SW", "Swisscom", "CH", "Télécom"),
    # ── Suisse — autres grandes valeurs ──
    ("SGSN.SW", "SGS", "CH", "Services"),
    ("BAER.SW", "Julius Baer", "CH", "Finance"),
    ("STMN.SW", "Straumann", "CH", "Santé"),
    ("TEMN.SW", "Temenos", "CH", "Tech"),
    ("SCHP.SW", "Schindler", "CH", "Industrie"),
    ("VACN.SW", "VAT Group", "CH", "Tech"),
    ("BALN.SW", "Bâloise", "CH", "Assurance"),
    # ── France — CAC 40 / grandes valeurs ──
    ("MC.PA", "LVMH", "FR", "Luxe"),
    ("OR.PA", "L'Oréal", "FR", "Conso. déf."),
    ("RMS.PA", "Hermès", "FR", "Luxe"),
    ("TTE.PA", "TotalEnergies", "FR", "Énergie"),
    ("SAN.PA", "Sanofi", "FR", "Santé"),
    ("AIR.PA", "Airbus", "FR", "Industrie"),
    ("AI.PA", "Air Liquide", "FR", "Matériaux"),
    ("SU.PA", "Schneider Electric", "FR", "Industrie"),
    ("EL.PA", "EssilorLuxottica", "FR", "Santé"),
    ("DG.PA", "Vinci", "FR", "Industrie"),
    ("CS.PA", "AXA", "FR", "Assurance"),
    ("BNP.PA", "BNP Paribas", "FR", "Finance"),
    ("SAF.PA", "Safran", "FR", "Industrie"),
    ("KER.PA", "Kering", "FR", "Luxe"),
    ("BN.PA", "Danone", "FR", "Conso. déf."),
    ("RI.PA", "Pernod Ricard", "FR", "Conso. déf."),
    ("DSY.PA", "Dassault Systèmes", "FR", "Tech"),
    ("ACA.PA", "Crédit Agricole", "FR", "Finance"),
    ("SGO.PA", "Saint-Gobain", "FR", "Matériaux"),
    ("STLAP.PA", "Stellantis", "FR", "Conso. cycl."),
    ("LR.PA", "Legrand", "FR", "Industrie"),
    ("PUB.PA", "Publicis", "FR", "Services"),
    ("CAP.PA", "Capgemini", "FR", "Tech"),
    ("GLE.PA", "Société Générale", "FR", "Finance"),
    ("ENGI.PA", "Engie", "FR", "Utilities"),
    ("VIE.PA", "Veolia", "FR", "Utilities"),
    ("HO.PA", "Thales", "FR", "Industrie"),
    ("ML.PA", "Michelin", "FR", "Conso. cycl."),
    ("EN.PA", "Bouygues", "FR", "Industrie"),
    ("SW.PA", "Sodexo", "FR", "Services"),
    ("RMS.PA", "Hermès", "FR", "Luxe"),
    # ── Allemagne — DAX / grandes valeurs ──
    ("SAP.DE", "SAP", "DE", "Tech"),
    ("SIE.DE", "Siemens", "DE", "Industrie"),
    ("ALV.DE", "Allianz", "DE", "Assurance"),
    ("DTE.DE", "Deutsche Telekom", "DE", "Télécom"),
    ("MUV2.DE", "Munich Re", "DE", "Assurance"),
    ("AIR.DE", "Airbus", "DE", "Industrie"),
    ("MRK.DE", "Merck KGaA", "DE", "Santé"),
    ("MBG.DE", "Mercedes-Benz", "DE", "Conso. cycl."),
    ("BMW.DE", "BMW", "DE", "Conso. cycl."),
    ("VOW3.DE", "Volkswagen", "DE", "Conso. cycl."),
    ("DHL.DE", "DHL Group", "DE", "Industrie"),
    ("ADS.DE", "Adidas", "DE", "Conso. cycl."),
    ("BAS.DE", "BASF", "DE", "Matériaux"),
    ("BAYN.DE", "Bayer", "DE", "Santé"),
    ("DB1.DE", "Deutsche Börse", "DE", "Finance"),
    ("IFX.DE", "Infineon", "DE", "Tech"),
    ("RWE.DE", "RWE", "DE", "Utilities"),
    ("EOAN.DE", "E.ON", "DE", "Utilities"),
    ("DBK.DE", "Deutsche Bank", "DE", "Finance"),
    ("HEN3.DE", "Henkel", "DE", "Conso. déf."),
    ("BEI.DE", "Beiersdorf", "DE", "Conso. déf."),
    ("FRE.DE", "Fresenius", "DE", "Santé"),
    ("FME.DE", "Fresenius Medical", "DE", "Santé"),
    ("HNR1.DE", "Hannover Re", "DE", "Assurance"),
    ("SY1.DE", "Symrise", "DE", "Matériaux"),
    ("MTX.DE", "MTU Aero Engines", "DE", "Industrie"),
    ("VNA.DE", "Vonovia", "DE", "Immobilier"),
    ("ENR.DE", "Siemens Energy", "DE", "Industrie"),
    ("SHL.DE", "Siemens Healthineers", "DE", "Santé"),
    ("P911.DE", "Porsche AG", "DE", "Conso. cycl."),
    # ── Pays-Bas ──
    ("ASML.AS", "ASML", "NL", "Tech"),
    ("PRX.AS", "Prosus", "NL", "Tech"),
    ("INGA.AS", "ING Group", "NL", "Finance"),
    ("AD.AS", "Ahold Delhaize", "NL", "Conso. déf."),
    ("WKL.AS", "Wolters Kluwer", "NL", "Services"),
    ("PHIA.AS", "Philips", "NL", "Santé"),
    ("HEIA.AS", "Heineken", "NL", "Conso. déf."),
    ("ASM.AS", "ASM International", "NL", "Tech"),
    ("AKZA.AS", "Akzo Nobel", "NL", "Matériaux"),
    ("DSFIR.AS", "DSM-Firmenich", "NL", "Matériaux"),
    ("ADYEN.AS", "Adyen", "NL", "Tech"),
    ("KPN.AS", "KPN", "NL", "Télécom"),
    ("RAND.AS", "Randstad", "NL", "Services"),
    # ── Royaume-Uni (LSE, prix en GBp) ──
    ("AZN.L", "AstraZeneca", "GB", "Santé"),
    ("SHEL.L", "Shell", "GB", "Énergie"),
    ("HSBA.L", "HSBC", "GB", "Finance"),
    ("ULVR.L", "Unilever", "GB", "Conso. déf."),
    ("BP.L", "BP", "GB", "Énergie"),
    ("GSK.L", "GSK", "GB", "Santé"),
    ("DGE.L", "Diageo", "GB", "Conso. déf."),
    ("RIO.L", "Rio Tinto", "GB", "Matériaux"),
    ("REL.L", "RELX", "GB", "Services"),
    ("GLEN.L", "Glencore", "GB", "Matériaux"),
    ("BATS.L", "BAT", "GB", "Conso. déf."),
    ("LSEG.L", "London Stock Exchange", "GB", "Finance"),
    ("NG.L", "National Grid", "GB", "Utilities"),
    ("BARC.L", "Barclays", "GB", "Finance"),
    ("LLOY.L", "Lloyds Banking", "GB", "Finance"),
    ("VOD.L", "Vodafone", "GB", "Télécom"),
    ("PRU.L", "Prudential", "GB", "Assurance"),
    ("HLN.L", "Haleon", "GB", "Conso. déf."),
    ("CPG.L", "Compass Group", "GB", "Services"),
    ("AAL.L", "Anglo American", "GB", "Matériaux"),
    ("RR.L", "Rolls-Royce", "GB", "Industrie"),
    ("EXPN.L", "Experian", "GB", "Services"),
    ("BA.L", "BAE Systems", "GB", "Industrie"),
    ("IMB.L", "Imperial Brands", "GB", "Conso. déf."),
    ("RKT.L", "Reckitt", "GB", "Conso. déf."),
    ("SSE.L", "SSE", "GB", "Utilities"),
    ("STAN.L", "Standard Chartered", "GB", "Finance"),
    ("AV.L", "Aviva", "GB", "Assurance"),
    ("TSCO.L", "Tesco", "GB", "Conso. déf."),
    ("SGRO.L", "Segro", "GB", "Immobilier"),
    # ── Italie ──
    ("ENEL.MI", "Enel", "IT", "Utilities"),
    ("ISP.MI", "Intesa Sanpaolo", "IT", "Finance"),
    ("ENI.MI", "Eni", "IT", "Énergie"),
    ("UCG.MI", "UniCredit", "IT", "Finance"),
    ("RACE.MI", "Ferrari", "IT", "Conso. cycl."),
    ("G.MI", "Generali", "IT", "Assurance"),
    ("STLAM.MI", "Stellantis", "IT", "Conso. cycl."),
    ("PRY.MI", "Prysmian", "IT", "Industrie"),
    ("MONC.MI", "Moncler", "IT", "Luxe"),
    ("SRG.MI", "Snam", "IT", "Utilities"),
    ("TRN.MI", "Terna", "IT", "Utilities"),
    ("MB.MI", "Mediobanca", "IT", "Finance"),
    ("RECT.MI", "Recordati", "IT", "Santé"),
    # ── Espagne ──
    ("IBE.MC", "Iberdrola", "ES", "Utilities"),
    ("SAN.MC", "Banco Santander", "ES", "Finance"),
    ("ITX.MC", "Inditex", "ES", "Conso. cycl."),
    ("BBVA.MC", "BBVA", "ES", "Finance"),
    ("AENA.MC", "Aena", "ES", "Industrie"),
    ("FER.MC", "Ferrovial", "ES", "Industrie"),
    ("TEF.MC", "Telefónica", "ES", "Télécom"),
    ("AMS.MC", "Amadeus", "ES", "Tech"),
    ("CLNX.MC", "Cellnex", "ES", "Télécom"),
    ("ELE.MC", "Endesa", "ES", "Utilities"),
    ("RED.MC", "Redeia", "ES", "Utilities"),
    # ── Suède ──
    ("ATCO-A.ST", "Atlas Copco", "SE", "Industrie"),
    ("INVE-B.ST", "Investor AB", "SE", "Finance"),
    ("VOLV-B.ST", "Volvo", "SE", "Industrie"),
    ("ASSA-B.ST", "Assa Abloy", "SE", "Industrie"),
    ("ERIC-B.ST", "Ericsson", "SE", "Tech"),
    ("SAND.ST", "Sandvik", "SE", "Industrie"),
    ("EQT.ST", "EQT", "SE", "Finance"),
    ("HEXA-B.ST", "Hexagon", "SE", "Tech"),
    ("SEB-A.ST", "SEB", "SE", "Finance"),
    ("SHB-A.ST", "Handelsbanken", "SE", "Finance"),
    ("EVO.ST", "Evolution", "SE", "Conso. cycl."),
    ("ESSITY-B.ST", "Essity", "SE", "Conso. déf."),
    ("TELIA.ST", "Telia", "SE", "Télécom"),
    ("ALFA.ST", "Alfa Laval", "SE", "Industrie"),
    ("SWED-A.ST", "Swedbank", "SE", "Finance"),
    # ── Danemark ──
    ("NOVO-B.CO", "Novo Nordisk", "DK", "Santé"),
    ("DSV.CO", "DSV", "DK", "Industrie"),
    ("NZYM-B.CO", "Novonesis", "DK", "Matériaux"),
    ("MAERSK-B.CO", "Maersk", "DK", "Industrie"),
    ("CARL-B.CO", "Carlsberg", "DK", "Conso. déf."),
    ("ORSTED.CO", "Ørsted", "DK", "Utilities"),
    ("COLO-B.CO", "Coloplast", "DK", "Santé"),
    ("DANSKE.CO", "Danske Bank", "DK", "Finance"),
    ("GMAB.CO", "Genmab", "DK", "Santé"),
    ("VWS.CO", "Vestas Wind", "DK", "Industrie"),
    ("TRYG.CO", "Tryg", "DK", "Assurance"),
    # ── Finlande ──
    ("NDA-FI.HE", "Nordea Bank", "FI", "Finance"),
    ("KNEBV.HE", "Kone", "FI", "Industrie"),
    ("SAMPO.HE", "Sampo", "FI", "Assurance"),
    ("NESTE.HE", "Neste", "FI", "Énergie"),
    ("FORTUM.HE", "Fortum", "FI", "Utilities"),
    ("UPM.HE", "UPM-Kymmene", "FI", "Matériaux"),
    ("STERV.HE", "Stora Enso", "FI", "Matériaux"),
    ("NOKIA.HE", "Nokia", "FI", "Tech"),
    ("WRT1V.HE", "Wärtsilä", "FI", "Industrie"),
    # ── Norvège ──
    ("EQNR.OL", "Equinor", "NO", "Énergie"),
    ("DNB.OL", "DNB Bank", "NO", "Finance"),
    ("TEL.OL", "Telenor", "NO", "Télécom"),
    ("MOWI.OL", "Mowi", "NO", "Conso. déf."),
    ("NHY.OL", "Norsk Hydro", "NO", "Matériaux"),
    ("AKRBP.OL", "Aker BP", "NO", "Énergie"),
    ("ORK.OL", "Orkla", "NO", "Conso. déf."),
    # ── Belgique ──
    ("ABI.BR", "AB InBev", "BE", "Conso. déf."),
    ("KBC.BR", "KBC Group", "BE", "Finance"),
    ("UCB.BR", "UCB", "BE", "Santé"),
    ("SOLB.BR", "Solvay", "BE", "Matériaux"),
    ("GBLB.BR", "Groupe Bruxelles Lambert", "BE", "Finance"),
    ("ARGX.BR", "Argenx", "BE", "Santé"),
    ("UMI.BR", "Umicore", "BE", "Matériaux"),
    # ── Irlande ──
    ("KRZ.IR", "Kerry Group", "IE", "Conso. déf."),
    ("KRX.IR", "Kingspan", "IE", "Matériaux"),
    ("RYA.IR", "Ryanair", "IE", "Industrie"),
    ("FLTR.L", "Flutter Entertainment", "IE", "Conso. cycl."),
    ("SK3.IR", "Smurfit Kappa", "IE", "Matériaux"),
    # ── Autriche ──
    ("EBS.VI", "Erste Group", "AT", "Finance"),
    ("VER.VI", "Verbund", "AT", "Utilities"),
    ("OMV.VI", "OMV", "AT", "Énergie"),
    ("ANDR.VI", "Andritz", "AT", "Industrie"),
    # ── Portugal ──
    ("EDP.LS", "EDP", "PT", "Utilities"),
    ("GALP.LS", "Galp Energia", "PT", "Énergie"),
    ("JMT.LS", "Jerónimo Martins", "PT", "Conso. déf."),
]

# Dédoublonnage (certaines valeurs ont plusieurs cotations) — on garde la 1ʳᵉ.
_seen = set()
TICKERS = [t for t in TICKERS if not (t[0] in _seen or _seen.add(t[0]))]
